# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ethiery/.local/share/umake/ide/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/ethiery/.local/share/umake/ide/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ethiery/Cours/PRCD/TDP/TDP6/funWithLife

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ethiery/Cours/PRCD/TDP/TDP6/funWithLife

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ethiery/.local/share/umake/ide/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ethiery/.local/share/umake/ide/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ethiery/Cours/PRCD/TDP/TDP6/funWithLife/CMakeFiles /home/ethiery/Cours/PRCD/TDP/TDP6/funWithLife/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ethiery/Cours/PRCD/TDP/TDP6/funWithLife/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named funWithLife

# Build rule for target.
funWithLife: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 funWithLife
.PHONY : funWithLife

# fast build rule for target.
funWithLife/fast:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/build
.PHONY : funWithLife/fast

Board.o: Board.c.o

.PHONY : Board.o

# target to build an object file
Board.c.o:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/Board.c.o
.PHONY : Board.c.o

Board.i: Board.c.i

.PHONY : Board.i

# target to preprocess a source file
Board.c.i:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/Board.c.i
.PHONY : Board.c.i

Board.s: Board.c.s

.PHONY : Board.s

# target to generate assembly for a file
Board.c.s:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/Board.c.s
.PHONY : Board.c.s

DistributedBoard.o: DistributedBoard.c.o

.PHONY : DistributedBoard.o

# target to build an object file
DistributedBoard.c.o:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/DistributedBoard.c.o
.PHONY : DistributedBoard.c.o

DistributedBoard.i: DistributedBoard.c.i

.PHONY : DistributedBoard.i

# target to preprocess a source file
DistributedBoard.c.i:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/DistributedBoard.c.i
.PHONY : DistributedBoard.c.i

DistributedBoard.s: DistributedBoard.c.s

.PHONY : DistributedBoard.s

# target to generate assembly for a file
DistributedBoard.c.s:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/DistributedBoard.c.s
.PHONY : DistributedBoard.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/main.c.s
.PHONY : main.c.s

runMpiOMP.o: runMpiOMP.c.o

.PHONY : runMpiOMP.o

# target to build an object file
runMpiOMP.c.o:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runMpiOMP.c.o
.PHONY : runMpiOMP.c.o

runMpiOMP.i: runMpiOMP.c.i

.PHONY : runMpiOMP.i

# target to preprocess a source file
runMpiOMP.c.i:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runMpiOMP.c.i
.PHONY : runMpiOMP.c.i

runMpiOMP.s: runMpiOMP.c.s

.PHONY : runMpiOMP.s

# target to generate assembly for a file
runMpiOMP.c.s:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runMpiOMP.c.s
.PHONY : runMpiOMP.c.s

runMpiSeq.o: runMpiSeq.c.o

.PHONY : runMpiSeq.o

# target to build an object file
runMpiSeq.c.o:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runMpiSeq.c.o
.PHONY : runMpiSeq.c.o

runMpiSeq.i: runMpiSeq.c.i

.PHONY : runMpiSeq.i

# target to preprocess a source file
runMpiSeq.c.i:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runMpiSeq.c.i
.PHONY : runMpiSeq.c.i

runMpiSeq.s: runMpiSeq.c.s

.PHONY : runMpiSeq.s

# target to generate assembly for a file
runMpiSeq.c.s:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runMpiSeq.c.s
.PHONY : runMpiSeq.c.s

runOMP.o: runOMP.c.o

.PHONY : runOMP.o

# target to build an object file
runOMP.c.o:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runOMP.c.o
.PHONY : runOMP.c.o

runOMP.i: runOMP.c.i

.PHONY : runOMP.i

# target to preprocess a source file
runOMP.c.i:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runOMP.c.i
.PHONY : runOMP.c.i

runOMP.s: runOMP.c.s

.PHONY : runOMP.s

# target to generate assembly for a file
runOMP.c.s:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runOMP.c.s
.PHONY : runOMP.c.s

runPthreads.o: runPthreads.c.o

.PHONY : runPthreads.o

# target to build an object file
runPthreads.c.o:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runPthreads.c.o
.PHONY : runPthreads.c.o

runPthreads.i: runPthreads.c.i

.PHONY : runPthreads.i

# target to preprocess a source file
runPthreads.c.i:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runPthreads.c.i
.PHONY : runPthreads.c.i

runPthreads.s: runPthreads.c.s

.PHONY : runPthreads.s

# target to generate assembly for a file
runPthreads.c.s:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runPthreads.c.s
.PHONY : runPthreads.c.s

runSeq.o: runSeq.c.o

.PHONY : runSeq.o

# target to build an object file
runSeq.c.o:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runSeq.c.o
.PHONY : runSeq.c.o

runSeq.i: runSeq.c.i

.PHONY : runSeq.i

# target to preprocess a source file
runSeq.c.i:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runSeq.c.i
.PHONY : runSeq.c.i

runSeq.s: runSeq.c.s

.PHONY : runSeq.s

# target to generate assembly for a file
runSeq.c.s:
	$(MAKE) -f CMakeFiles/funWithLife.dir/build.make CMakeFiles/funWithLife.dir/runSeq.c.s
.PHONY : runSeq.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... funWithLife"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... DistributedBoard.o"
	@echo "... DistributedBoard.i"
	@echo "... DistributedBoard.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... runMpiOMP.o"
	@echo "... runMpiOMP.i"
	@echo "... runMpiOMP.s"
	@echo "... runMpiSeq.o"
	@echo "... runMpiSeq.i"
	@echo "... runMpiSeq.s"
	@echo "... runOMP.o"
	@echo "... runOMP.i"
	@echo "... runOMP.s"
	@echo "... runPthreads.o"
	@echo "... runPthreads.i"
	@echo "... runPthreads.s"
	@echo "... runSeq.o"
	@echo "... runSeq.i"
	@echo "... runSeq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

